- hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims
  tasks:
    - name: Use dbrc module to retrieve catalog database details
      ibm.ibm_zos_ims.ims_dbrc:
        steplib:
          - "{{ steplib }}"
        dbd_lib: "{{ dbdlib }}"
        recon1: "{{ recon_hlq }}.RECON1"
        recon2: "{{ recon_hlq }}.RECON2"
        recon3: "{{ recon_hlq }}.RECON3"
        command:
          - LIST.DB DBD({{ database_name }})
      register: registered_dbs_output

    - name: Display output
      ansible.builtin.debug:
        var: registered_dbs_output
